# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9yPYAH5xgQi4vMSLUS7o9c8cbQw8jG4
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

import pandas as pd
# Replace 'your_dataset.csv' with the actual name of your dataset
df = pd.read_csv('climatedata 1 (1).csv')
df.head()
df.describe()

correlation_matrix = df.corr()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 18))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Replace 'your_dataset.csv' with the actual filename or URL
df = pd.read_csv('climatedata 1 (1).csv')

# Set the index of the DataFrame to the first column if it contains the years or time-related data
df.set_index(df.columns[0], inplace=True)

# Plotting trend graphs for selected columns
columns_of_interest = ['Afghanistan', 'Bahrain', 'Canada(Urban population)', 'Canada(Access to electricity (% of population))']

plt.figure(figsize=(12, 8))

for column in columns_of_interest:
    plt.plot(df.index, df[column], label=column)

plt.title('Trend Graphs for Selected Countries')
plt.xlabel('Year or Time')
plt.ylabel('Values')
plt.legend()
plt.show()


# Bar graph
plt.figure(figsize=(10, 6))
df_bar = df[columns_of_interest].mean()  # Using mean values for the bar graph
df_bar.plot(kind='bar', color='skyblue')
plt.title('Average Values for Selected Countries')
plt.xlabel('Country/Indicator')
plt.ylabel('Average Values')
plt.show()

# Pie chart
plt.figure(figsize=(8, 8))
plt.pie(df_bar, labels=df_bar.index, autopct='%1.1f%%', startangle=90, colors=['lightcoral', 'lightblue', 'lightgreen', 'lightpink'])
plt.title('Percentage Distribution of Average Values for Selected Countries/Indicators')
plt.show()